

# from langchain_openai import ChatOpenAI
# from dotenv import load_dotenv
# import streamlit as st

# load_dotenv()

# st.header("Research Tool")

# user_input = st.text_input('Enter your prompt')

# if st.button('Summarize'):
#     result = model.invoke(user_input)
#     st.write(result.content)


# this is  static prompt where full acces to asking anything is users hand 
#the can asked any question in any format and in any lines  there is no limitation to asking in the static prompts 